version: '3'

services:
  postgres:
    restart: always
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: Your_password123

  # webapi:
  #   container_name: webapi
  #   build:
  #     context: .
  #     dockerfile: Net5CoreWebAPI/Dockerfile
  #   restart: always
  #   ports:
  #     - 5000:80
  #   depends_on:
  #     - postgres
    # environment:
    #   ConnectionString: Server=postgres;Database=webapp;User Id=sa;Password=Your_password123;
    #   ConnectionString_Postgres: Host=localhost;Database=webapp;Username=postgres_user;Password=Your_password123